added multiavatar api to existing random avatar generators
TheRustyPickle/Chirp pull request #49
Opened 2023-10-02 17:01 UTC by aybeedee

# Issue

Closes #46 

# Description

Added [Multiavatar](https://api.multiavatar.com/) API to the existing random avatar generator options.

2023-10-02 19:04 UTC, TheRustyPickle requested changes

2023-10-02 19:04 UTC, TheRustyPickle commented on gui/src/utils.rs
>      match selected_choice {
The `choices` array needs to be updated with `multiavatar` otherwise this choice would never be selected.

2023-10-03 05:37 UTC, aybeedee commented on gui/src/utils.rs
>      match selected_choice {
Overlooked it! made the change now.

2023-10-03 12:46 UTC, TheRustyPickle approved these changes

2023-10-03 12:46 UTC, merged

2023-10-03 12:47 UTC, TheRustyPickle commented
Thank you for your contribution, @aybeedee! You can take a look at the other issues if you are interested in contributing further.

2023-10-03 13:25 UTC, aybeedee commented
@TheRustyPickle I'll definitely go through them if I get more time. Also, I'm very new to Rust. What's up with the emphasis on snake case? Even the compiler suggests me to use it! I'm very used to camel and pascal case myself. Is there a particular reason for the preference? Or am I just too much of a newbie to this ecosystem.

2023-10-03 13:37 UTC, TheRustyPickle commented
@aybeedee I believe it is the official Rust style of writing functions, variables, etc. The use of the snake case is emphasized in the [official Rust book](https://doc.rust-lang.org/book/ch03-03-how-functions-work.html#functions) as well.